### ISSUE TITLE
Build number policy

### ISSUE THREAD

**Issue by AntoineTurmel** [nightingale-media-player/nightingale-hacking#255]
I was wondering if we should keep the build number... it's not really useful in my opinion since you can check version + date already...

Buildnumber was used on Songbird and incremented at each commit (if I remember well), and we don't really do so.

**Comment by rsjtdrjgfuzkfg** [comment]
https://github.com/nightingale-media-player/nightingale-hacking/pull/334

**Comment by freaktechnik** [comment]
No, you can't. You could make github corss refer to the issue by mentioning it in the pull's description, like it did for the commit. I'm also wondering if this kind of mention in the commit will auto-fix this bug as soon as it's merged.

**Comment by freaktechnik** [comment]
As I commented in #334:

> Should we check for git's presence if --enable-official or --enable-nightly is set?

**Comment by rsjtdrjgfuzkfg** [comment]
@freaktechnik probably a good idea, if you know a fail-safe way to do that cross-platform? I'm not too sure what's possible in all shells used to build Nightingale. But it is not really bad if we don't imho.
