### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by freaktechnik** [nightingale-media-player/nightingale-hacking#267]
I think at least on linux we should implement a make install command, as this is defacto standard there. It should do something along the lines of copying compiled/dist/ to /usr/lib/ and maybe copy the desktop file from debian/ and make a symlink in usr/bin to the nightingale binary.

**Comment by darealshinji** [comment]
I think this issue can be closed, right?

**Comment by freaktechnik** [comment]
I think so, as this won't be used on OSX and Windows.
