### ISSUE TITLE
NG doesn't play music

### ISSUE THREAD

**Issue by darealshinji** [nightingale-media-player/nightingale-hacking#302]
I've just downloaded the source and compiled it. NG runs but it doesn't play any music. The version currently installed on my system works fine however  (Git snapshot from 2014-05-24).
Here's the output from the error console:
```
Fehler: uncaught exception: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [sbIMediacoreSequencer.playView]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://songbird/content/bindings/playlist.xml :: sendPlayEvent :: line 1616"  data: no]
```
My system: Linux Mint 17, x86_64 Linux 3.13.0-27-generic

**Comment by darealshinji** [comment]
I've never had any issues like this again.

**Comment by freaktechnik** [comment]
This should still happen with non-english langpacks, unless @AntoineTurmel since built langpacks.
