### ISSUE TITLE
Display remaining track time on left side

### ISSUE THREAD

**Issue by darealshinji** [nightingale-media-player/nightingale-hacking#323]
![](http://s1.directupload.net/images/140911/lnlbd7qv.png)
It's probably just my personal preference but I think it'd be better to let the left display show the current or remaining time while the right display only shows the full track length.

**Comment by PanderMusubi** [comment]
Is this feature request still valid?

**Comment by darealshinji** [comment]
I'd still like it to be toggleable like that.
