### ISSUE TITLE
Nightingale Will Not Play on Archlinux (neither gst 0.10 nor gst 1.0)

### ISSUE THREAD

**Issue by ilikenwf** [nightingale-media-player/nightingale-hacking#340]
System:
Current Archlinux, testing repo enabled
Nouveau with nouveau vdpau
Nightingale-git and the current milestone release

Nightingale refuses to play music - it will load up a flac or mp3, and get the length and title, but then does not play and instead just sits there. Only error so far was an error about an mpg layer 1 decoder for mp3's. I'm thinking maybe Arch has changed their gst packages somehow as both 0.10 and 1.0 worked previously, or I have a system configuration issue.

Could some other Arch user give it a try, and confirm or deny my issue?

**Comment by darealshinji** [comment]
Are all the gstreamer codecs installed? Maybe gstreamer0.10-plugins-bad and/or gstreamer0.10-plugins-ugly is missing but required to play the files? Does ogg vorbis play?

**Comment by ilikenwf** [comment]
I have all the codecs for sure...

gst-libav 1.4.5-1
gst-plugins-bad 1.4.5-1
gst-plugins-base 1.4.5-1
gst-plugins-base-libs 1.4.5-1
gst-plugins-good 1.4.5-1
gst-plugins-ugly 1.4.5-1
gstreamer 1.4.5-1
gstreamer-vaapi 0.5.10-1
gstreamer0.10 0.10.36-4
gstreamer0.10-bad 0.10.23-8
gstreamer0.10-bad-plugins 0.10.23-8
gstreamer0.10-base 0.10.36-3
gstreamer0.10-base-plugins 0.10.36-3
gstreamer0.10-ffmpeg 0.10.13-2
gstreamer0.10-good 0.10.31-6
gstreamer0.10-good-plugins 0.10.31-6

**Comment by luisgmarine** [comment]
@ilikenwf  I ran into the same problem just about a month ago when I was installing a fresh copy of Arch Linux.  I ran 'pacman -Q | grep gst' on my machine and below are the only packages that I have and you don't.  

gstreamer0.10-ugly 0.10.19-13
gstreamer0.10-ugly-plugins 0.10.19-13
gstreamer0.10-vaapi 0.5.9-1

Try installing those packages and let us know if works.

**Comment by ilikenwf** [comment]
Well, with the 0.10 version that may make a difference, but with 1.0 that
makes no sense. No joy with the 1.0 version, I'll have to rebuild 0.10 a
little later. The vaapi plugin isn't in any repos and also isn't in AUR, so
I'm not sure where you found it.

**Comment by luisgmarine** [comment]
It appears to be a package that was dropped and is still lingering on my system.  You can exclude that one.

**Comment by wilspi** [comment]
i have got nightingale on arch which works fine
I ran 'pacman -Q | grep gst' and got the following list if that might help :
![screenshot from 2015-03-24 09 56 51](https://cloud.githubusercontent.com/assets/7404121/6795788/235fd646-d20c-11e4-92ef-8af17ab77ff6.png)

gstreamer
![screenshot from 2015-03-24 09 53 47](https://cloud.githubusercontent.com/assets/7404121/6795757/ba43e288-d20b-11e4-895d-850cbd1522be.png)

**Comment by ilikenwf** [comment]
The issue seems resolved now - guessing I had a bad package or something? Either way, closing.
