### ISSUE TITLE
MP3 playback not working on fedora 21

### ISSUE THREAD

**Issue by steve80289** [nightingale-media-player/nightingale-hacking#342]
When clicking on mp3 files, nightingale will not respond. FLAC files work fine. 

Version: Nightingale 1.12.1, Build 2454 (20140112233527)

**Comment by freaktechnik** [comment]
Do you have the gstreamer 0.1 ugly plugins installed?

**Comment by steve80289** [comment]
Yeah.

Installed Packages
gstreamer.x86_64                                         0.10.36-11.fc21             @System          
gstreamer-plugins-bad-free.x86_64                        0.10.23-24.fc21             @System          
gstreamer-plugins-base.x86_64                            0.10.36-12.fc21             @System          
gstreamer-plugins-espeak.x86_64                          0.4.0-5.fc21                @System          
gstreamer-plugins-good.x86_64                            0.10.31-13.fc21             @System          
gstreamer-tools.x86_64                                   0.10.36-11.fc21             @System          
gstreamer1.x86_64                                        1.4.5-1.fc21                @System          
gstreamer1-libav.x86_64                                  1.4.3-1.fc21                @System          
gstreamer1-plugins-bad-free.x86_64                       1.4.5-2.fc21                @System          
gstreamer1-plugins-bad-freeworld.x86_64                  1.4.3-1.fc21                @System          
gstreamer1-plugins-base.x86_64                           1.4.5-1.fc21                @System          
gstreamer1-plugins-good.x86_64                           1.4.5-1.fc21                @System          
gstreamer1-plugins-ugly.x86_64                           1.4.3-1.fc21                @System

**Comment by steve80289** [comment]
oh, 0.10 got it! Installing now!

**Comment by steve80289** [comment]
It works now! Thanks!
