### ISSUE TITLE
Last.fm Scrobbler and mLyrics wont work

### ISSUE THREAD

**Issue by wilspi** [nightingale-media-player/nightingale-hacking#344]
I have got Arch Linux and Nightingale (Version: Nightingale 1.13a, Build 0 (20150324080901))
Last.fm and mLyrics addons worked just fine with the previous nightingale version

**Comment by freaktechnik** [comment]
Have you downloaded versions that actually are compatible with 1.13a?

**Comment by wilspi** [comment]
I tried to install the latest addons but while installing it shows
![screenshot from 2015-04-03 19 19 15](https://cloud.githubusercontent.com/assets/7404121/6983048/efdcfdb6-da36-11e4-8530-f68c0266b26d.png)
and later it shows its not compatible with 1.13a

I am guessing there are no versions compatible with 1.13a, is there?

**Comment by freaktechnik** [comment]
For MLyrics I'm not sute, but for last.fm you can find them in our sourceforge in the nightlies folder, as nightingale-git on arch builds the trunk version 1.13a (that's why there is an a).

For MLyrics you would have to look at its source repo (which is somewhere here on github).

**Comment by wilspi** [comment]
yeah that did work fine
For MLyrics : 
"I dont know where it is but i will find it and fix it."  :D

btw I think you guys should update the site.

**Comment by freaktechnik** [comment]
@wilspi: 1.13a is not an official release yet, the arch package is basically a Nightly version of Nightingale.
Further we (well, I) are working on a new site.

**Comment by wilspi** [comment]
@freaktechnik i didnt know about that. you guys are dong a great work.
looking forward to see the new site.  (Y)

**Comment by PanderMusubi** [comment]
Could the next stable release be shipped with Ubuntu instead via a nightly on a PPA? In order to get all sorted in time I am willing to donate via some bounties. Coming back to this issue, does this one supersede https://github.com/nightingale-media-player/nightingale-hacking/issues/57 ? Because I would like to contribute to a bounty getting last.fm (and libre.fm) scroblling supported again.

**Comment by freaktechnik** [comment]
I am not sure if you understand what this issue and #57 are about. Also, the whole ubuntu stuff is covered in multiple places.

**Comment by PanderMusubi** [comment]
That the deb packaging for Ubuntu is in multiple and longstanding issues is clear to me.

Issues I would like to contribute to is to get support for scrobbling last.fm (and libre.fm) in Nightingale. At the moment, I get the same error as is reported in this issue. For that, I would like to make a contribution via BountySource but was at the same time wondering if 57 is relevant (still open) in the entire scope of last.fm support.
