### ISSUE TITLE
Issue with soundcloud-app: can't edit settings for logging into soundcloud

### ISSUE THREAD

**Issue by Bongsunra** [nightingale-media-player/nightingale-hacking#345]
I can use the soundcloudapp but cannot edit the settings for logging into my soundcloud user account.
Is there any solution for this problem?

Best regards,

Bongsunra

**Comment by freaktechnik** [comment]
You should be able to log in and out in the right bottom corner of the nightingale window.

**Comment by Bongsunra** [comment]
Perfect, thanks! That was fast!
Great program btw!

Have a nice weekend,

Bongsunra

**Comment by PanderMusubi** [comment]
For nightingale 1.13a-0~13186~ubuntu15.04.1 logging in results in endless spinner activity without getting to a logged in situation. What log files can I add to get this solved? Logging in to the website via nightingale resutls in

Sorry! Something went wrong

Is your network connection unstable or browser outdated?"

**Comment by freaktechnik** [comment]
Hmm, it's possible that the soundcloud login needs technologies we don't support yet. Could you please open a new issue, since this is for sure unrelated?

**Comment by PanderMusubi** [comment]
Done, please see https://github.com/nightingale-media-player/nightingale-hacking/issues/351
