### ISSUE TITLE
 Nightingale audio player skips to next song before it ends

### ISSUE THREAD

**Issue by kaptainpepyn** [nightingale-media-player/nightingale-hacking#346]
When I use Nightingale to listen to music, it plays the first song on the list and skip to the next before it finished the first. It does that to any types of file and music. Is there a default setting that could provoke that? Anyone as a suggestion on how to fix that? I tried changing number in the option/playback section and it did'nt work.

Thanks and have a nice days.

-Kaptainpepyn.

**Comment by darealshinji** [comment]
That doesn't sound normal to me.
How much does it skip? What version are you using and what's your OS?

**Comment by kaptainpepyn** [comment]
It always skip the last second of a song, and often more than that. It could go up to the last fifteen seconds of a song.

I'm using Windows 7, 64-bit
My pc as 16 GB of ram and it's an Intel(R) i7-4770 CPU. The sound card is onboard

Thanks.

**Comment by kaptainpepyn** [comment]
My music's files are in mp3, mpeg-4, aiff and wav format.

**Comment by freaktechnik** [comment]
What numbers did you try for the playback buffer? Also, I assume, you're using Nightingale 1.12?

**Comment by kaptainpepyn** [comment]
Hi.
I'm using NG 1.12.1 (don't if the «.1» change something). The output buffer it is set to 2000 ms. I tried 10000, but the result is the same. Streaming buffer is at 128kb.
Thanks.

**Comment by kaptainpepyn** [comment]
Also, when it plays a song, before the end, it will display the next song to be played. Like the software is in a hurry or something. Strange. Thank you guy for taking the time to solve my puzzle, :) .

**Comment by kaptainpepyn** [comment]
I did more tests and there's a consistency in my problem. Each songs ends exactly 4,5 seconds before the end of there running time. Because some songs have long fade out or a few seconds of silence at the end, I thought it was not regular, but it is. Does this give anyone a clue?

Thanks again.

**Comment by kaptainpepyn** [comment]
Hi guys, i again did  more tests. When I set the output playback between 100 ms and 250 ms, it seems to resolve my problem. At 500 ms, it cuts 2 second of the end of each songs. At 1000 ms, it's about 4 seconds, at 10000 ms, it's 20 seconds. I know it all sounds weird. It could be a "computer personality" issue. Anyway, I'll let it at 250 ms for the next few days and if the bug does'nt repeat itself, this issue will be closed and me and my computer will go see a "couple's psychiatrist". ;)

**Comment by kaptainpepyn** [comment]
I've been listening to my music for 24 hours now and everything seems to be o.k.. Software is fine, it was just a setting problem.

Thanks and happy spring!
