### ISSUE TITLE
Nightingale no longer authenticating correctly after Last.fm site update

### ISSUE THREAD

**Issue by ben-xo** [nightingale-media-player/nightingale-hacking#360]
Hi there,

I work at Last.fm and Nightingale doesn't seem to be following our app login flow correctly. This is customer impacting as some users have complained that they're no longer able to scrobble as they can't log in.

The correct API auth flow docs are available at http://www.last.fm/api/auth

Nightingale appears to call `auth.getToken`, then sends a user to an authorisation page with this token.

The expected next step is either that the website triggers a callback URL (which can be a custom URL handler such as nightingale://) or that the application then calls `auth.getSession` . However that final call never happens. 

Perhaps you are screen scraping the result page?

**Comment by freaktechnik** [comment]
Our last.fm implementation is pretty ancient and I'm actually not surprised it's finally broken. Thanks for reporting it to us, though we should have looked into upgrading our Last.fm extension earlier on...
