### ISSUE TITLE
Nightingale not integrated with the latest last.fm update

### ISSUE THREAD

**Issue by lolscience** [nightingale-media-player/nightingale-hacking#361]
Ever since the last.fm redesign nightingale hasn't scrobbled anything I've played.

**Comment by freaktechnik** [comment]
You need to update to a newer add-on version from http://addons.getinightingale.com (click download in the Last.fm add-on section in nightingale's browser). I haven't updated the last.fm version in the firstrun dialog yet.

EDIT: sadly we don't have autoupdate and the only way to communicate such new versions is via Twitter, Facebook and Google+ (Where it has been communicated a few days ago).
