### ISSUE TITLE
Build for Ubuntu 15.10 wily

### ISSUE THREAD

**Issue by PanderMusubi** [nightingale-media-player/nightingale-hacking#368]
Please, build nightingale also for UBuntu 15.10 wily on launchpad PPA. Currently https//ppa.launchpad.net/k-dg/litecoin/ubuntu/dists/wily/ is missing, causing errors in apt-get update. Fixing this will allow users to easily install and upgrade nightingale from their Ubuntu system. @AntoineTurmel 
##

**Comment by freaktechnik** [comment]
Oh, I forgot 15.10 was out. Also Antoine is the wrong person to ping on this, since I'm marked as maintainer of the stable package...
I assume you meant our PPA, not k-dg's litecoin one?

**Comment by PanderMusubi** [comment]
Yes, that is the one I mean, copy-paste error.

**Comment by Erikcht** [comment]
Build nightingale also for UBuntu 16.04 Xenial Xerus on launchpad PPA
https://github.com/nightingale-media-player/nightingale-hacking/issues/371

**Comment by freaktechnik** [comment]
So just fyi, this is blocked by the gcc5 switch, I'll have to look at this at some point.

**Comment by PanderMusubi** [comment]
Would be nice to see this appear under the Christmas tree.

**Comment by freaktechnik** [comment]
Oh, since it's related: the nightly PPA (ppa:nightingaleteam/nightingale-nightly) works on 15.10. It also takes a new approach on the whole taglib situation.

**Comment by PanderMusubi** [comment]
Thanks, also looking forward to seeing a new version on http://ppa.launchpad.net/nightingaleteam/nightingale-release/ubuntu

**Comment by darealshinji** [comment]
Closing since 15.10 is an outdated distro.

**Comment by PanderMusubi** [comment]
Will there be build for current Ubuntu versions such as 18.04 LTS? https://launchpad.net/~nightingaleteam/+archive/ubuntu/nightingale-release

**Comment by darealshinji** [comment]
There are currently issues building it on newer distros. As an alternative you can try to use an AppImage: https://github.com/nightingale-media-player/nightingale-hacking/issues/383
