### ISSUE TITLE
gcc W: missing sentinel in function call

### ISSUE THREAD

**Issue by awissu** [nightingale-media-player/nightingale-hacking#373]
Hi!
I get warnings after build:
[ 1848s] I: Function call needs to pass NULL-pointer as last argument
[ 1848s] E: nightingale missing-sentinel /home/abuild/rpmbuild/BUILD/nightingale-hacking-1.12.1+git.20151004.4e3f055/components/mediacore/gstreamer/src/sbGStreamerVideoTranscode.cpp:1358, 1367
See: https://build.opensuse.org/package/live_build_log/home:awissu:branches:home:awissu/nightingale/openSUSE_Leap_42.1/x86_64

**Comment by freaktechnik** [comment]
So I assume this is on OpenSUSE? Also, are you using the prebuilt deps, what gcc version are you using?

**Comment by awissu** [comment]
Also, are you using the prebuilt deps..
No. 
Here spec-file: https://build.opensuse.org/package/show/home:awissu:branches:home:awissu/nightingale

**Comment by freaktechnik** [comment]
The normal releases are (still) built against gstreamer0.10. The gstreamer-1.0 branch builds against gstreamer-1.0. EDIT: just checked the commit has (at least what I think is the commit hash) you build against, and it seems to be in the 1.0 branch.

**Comment by awissu** [comment]
I cloned a git repositories:
git clone --branch gstreamer-1.0 https://github.com/nightingale-media-player/nightingale-hacking.git
git clone --branch xul-192-new https://github.com/nightingale-media-player/nightingale-deps.git

**Comment by freaktechnik** [comment]
It seems according to the docs of gst, the last argument _should_ indeed be null (this is linked from the docs of the called functions): http://gstreamer.freedesktop.org/data/doc/gstreamer/1.0/gstreamer/html/gstreamer-GstStructure.html#gst-structure-new. The lines in question are https://github.com/nightingale-media-player/nightingale-hacking/blob/gstreamer-1.0/components/mediacore/gstreamer/src/sbGStreamerVideoTranscode.cpp#L1358 and https://github.com/nightingale-media-player/nightingale-hacking/blob/gstreamer-1.0/components/mediacore/gstreamer/src/sbGStreamerVideoTranscode.cpp#L1367.

I am not sure about how rest arguments and all that work in C, so I'm not sure if it's just some compilers etc. that require the last argument to be NULL.

**Comment by freaktechnik** [comment]
It's funny - in older commits most of those varidic functions are actually NULL terminated. I'm running a testbuild with NULLs added to those two lines.

**Comment by freaktechnik** [comment]
Okay, I've pushed a patch that adds the NULLs to the argument list. It still compiles for me, but it always has, so all it says, is that nothing got broken.

**Comment by awissu** [comment]
Ok.
Fixed.
