### ISSUE TITLE
Gapless playback on windows 10

### ISSUE THREAD

**Issue by Jelmerro** [nightingale-media-player/nightingale-hacking#380]
I was informed on both the website and the alternativeto page, that Nightingale supports gapless playback.
However, it doesn't seem to work for me. I'm using version 1.12.1, Build 2454 (20140111214227) on windows 10. It may be old, but it looks like it's the latest stable version. I have tried a lot of different buffer settings, and all have the same tiny pause when switching to the next song. All songs tested are CBR 320 mp3s and do have gapless playback using foobar2000.

**Comment by freaktechnik** [comment]
I am not aware that the website states that it supports it. Instead there is a bug open to implement it (sorry, can't search for it on mobile)
