### ISSUE TITLE
Enable reordering of tracks in play queue

### ISSUE THREAD

**Issue by Manko10** [nightingale-media-player/nightingale-hacking#96]
Track entries can't be reordered in the play queue. Dragging them only creates a copy. This is very unintuitive. Dragging a track should move it, not duplicate it. Copying of entries could be implemented with Alt + drag similar to duplicating layers in Photoshop.

**Comment by freaktechnik** [comment]
Sorry @luisgmarine, but I was tempted to add the missing lines in order to fix this issue. As you can see the nsIDragSession (passed as aSession) contains information about what the intent of the session is.

**Comment by luisgmarine** [comment]
No problem at all @freaktechnik.  You actually taught me something so I am a happy camper!

**Comment by freaktechnik** [comment]
@luisgmarine Well, I had to dig deep into documentations and other code to find that, I don't know all the nsAPIs...
